package bankingapp;
//import java.awt.Choice;
import java.util.ArrayList;
import java.util.Scanner;
public class BWN_Application {
	
	public static void main(String[] args) {


System.out.println("Hi! Welcome to Bridge Water National Bank! Would you like to check your Balance,go to Checkings Account or got to Savings Account");
//Choice bank_options = new Choice();

private void askQuestion() {
	while(true) {
		System.out.println();
		System.out.println();
		System.out.println();
		char response = Character.toUpperCase(scanner.nextLine().charAt(0));
}

//bank_options.add("Welcome to your Balance");
//bank_options.add("Welcome to your Checking Account");
//bank_options.add("Welcome to your Savings Account");		
}
{
	//Week 6
int bankingnumber = 0;
	System.out.println("Enter Banking Number");
	Scanner sc = new Scanner(System.in);
if(sc.hasNextInt()) {
	bankingnumber = sc.nextInt();
if(bankingnumber>1000)
	System.out.println("You entered a bank number" + bankingnumber);
else {
	System.out.println("This bank number doesn't exist"+ bankingnumber);
}
 }
// Week 7: Generic or Auditing/ Week 8: Encryption

String a = "b";
String b = "c";
String c = "d";
String d = "e";
String e = "f";
String f = "g";
String g = "h";
String h = "i";
String i = "j";
String j = "k";
String k = "l";
String l = "m";
String m = "n"; 
String n = "o";
String o = "p";
String p = "q";
String q = "r";
String r = "s";
String s = "t";
String t = "u";
String u = "v";
String v = "w";
String w = "x";
String x = "y";
String y = "z";
String z = "a";

String messages;
messages = v+a+r+n+e+y ;
messages = l+a+n+c+e;
messages = a+n+d+r+e+w;
messages = s+o+r+e+n;
messages = n+o+r+a;
messages = y+e+m+e+l+e;
messages = o+s+u+n ;
messages = k+e+n+n+y;
messages = c+a+r+t+m+a+n;
messages =  f+o+x+y;
messages = m+e+l+l+y;
System.out.println("Unless you are adminastration, you are not allowed to see any of these names:"+ messages);
ArrayList<String> Accountnumber = new ArrayList();
Accountnumber.add("456");
Accountnumber.add("121");
Accountnumber.add("831");
Accountnumber.add("510");
Accountnumber.add("365");
Accountnumber.add("279");
Accountnumber.add("876");
Accountnumber.add("831");
Accountnumber.add("498");
Accountnumber.add("365");

ArrayList<String>Accountname = new ArrayList();
Accountname.add("Varney");
Accountname.add("Lance");
Accountname.add("Andrew");
Accountname.add("Soren");
Accountname.add("Nora");
Accountname.add("Yemele");
Accountname.add("Osun");
Accountname.add("Kenny");
Accountname.add("Cartman");
Accountname.add("Foxy");
Accountname.add("Melly");


if(15>20) {
System.out.print("These accounts will be charged $15" + Accountname);
}else {
System.out.println("These account will be charged $15" + Accountname);
}
}
}
